name: Add Definition of Done checklist

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
    add-dod-comment:
      runs-on: ubuntu-latest
      steps:
      - name: Comment DoD checklist on PR
        uses: actions/github-script@v7
        with:
          script: |
            const checklist = String.raw`
            ### ✅ Definition of Done checklist
            - [ ] Clean code standards applied
            - [ ] Unitary tests completed
            - [ ] Usability test done
            - Tuleap management
              - [ ] Task Initial Effort updated
              - [ ] Task Remaining Effort updated
              - [ ] Status updated
            - [ ] Teams notification
            `;


            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: checklist
            });

