name: Add Definition of Done checklist

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
    add-dod-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment DoD checklist on PR
        uses: actions/github-script@v7
        with:
            script: |
            const checklist = String.raw`
      ### ✅ Definition of Done checklist

          - [ ] Meaningful title and valuable description in pull request
          - [ ] Code change tested manually if not covered by automated tests
          - [ ] Pull request linked to one or more issues/stories
          - [ ] Acceptance criteria of the linked stories satisfied
          - [ ] State of target branch maintained or improved after the code change
            - [ ] Agreed software engineering best practices upheld
          - [ ] Code change comprehended by those who approved it
        `;

  github.rest.issues.createComment({
  issue_number: context.issue.number,
  owner: context.repo.owner,
  repo: context.repo.repo,
  body: checklist
});

